In [1]:
import pandas as pd 
import matplotlib.pyplot as plt
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
import ipywidgets as widgets
from IPython.display import display

In [2]:
dataset= pd.read_csv('Crop and fertilizer dataset.csv')

In [3]:
dataset

,District_Name,Soil_color,Nitrogen,Phosphorus,Potassium,pH,Rainfall,Temperature,Crop,Fertilizer,Link
0,Kolhapur,Black,75,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
1,Kolhapur,Black,80,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
2,Kolhapur,Black,85,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
3,Kolhapur,Black,90,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
4,Kolhapur,Black,95,50,100,6.5,1000,20,Sugarcane,Urea,https://youtu.be/2t5Am0xLTOo
...,...,...,...,...,...,...,...,...,...,...,...
4508,Pune,Black,130,80,150,7.0,1400,30,Sugarcane,MOP,https://youtu.be/2t5Am0xLTOo
4509,Pune,Black,135,80,150,7.0,1400,30,Sugarcane,MOP,https://youtu.be/2t5Am0xLTOo
4510,Pune,Black,140,80,150,7.0,1400,30,Sugarcane,MOP,https://youtu.be/2t5Am0xLTOo
4511,Pune,Black,145,80,150,7.0,1400,30,Sugarcane,MOP,https://youtu.be/2t5Am0xLTOo
4512,Pune,Black,150,80,150,7.0,1400,30,Sugarcane,MOP,https://youtu.be/2t5Am0xLTOo

In [58]:

dataset.drop(columns=['Link'], inplace=True)

In [59]:
dataset

,District_Name,Soil_color,Nitrogen,Phosphorus,Potassium,pH,Rainfall,Temperature,Crop,Fertilizer
0,Kolhapur,Black,75,50,100,6.5,1000,20,Sugarcane,Urea
1,Kolhapur,Black,80,50,100,6.5,1000,20,Sugarcane,Urea
2,Kolhapur,Black,85,50,100,6.5,1000,20,Sugarcane,Urea
3,Kolhapur,Black,90,50,100,6.5,1000,20,Sugarcane,Urea
4,Kolhapur,Black,95,50,100,6.5,1000,20,Sugarcane,Urea
...,...,...,...,...,...,...,...,...,...,...
4508,Pune,Black,130,80,150,7.0,1400,30,Sugarcane,MOP
4509,Pune,Black,135,80,150,7.0,1400,30,Sugarcane,MOP
4510,Pune,Black,140,80,150,7.0,1400,30,Sugarcane,MOP
4511,Pune,Black,145,80,150,7.0,1400,30,Sugarcane,MOP
4512,Pune,Black,150,80,150,7.0,1400,30,Sugarcane,MOP

In [4]:
dataset.isnull().sum()

District_Name    0
Soil_color       0
Nitrogen         0
Phosphorus       0
Potassium        0
pH               0
Rainfall         0
Temperature      0
Crop             0
Fertilizer       0
Link             0
dtype: int64

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4513 entries, 0 to 4512
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   District_Name  4513 non-null   object
 1   Soil_color     4513 non-null   object
 2   Nitrogen       4513 non-null   int64
 3   Phosphorus     4513 non-null   int64
 4   Potassium      4513 non-null   int64
 5   pH             4513 non-null   float64
 6   Rainfall       4513 non-null   int64
 7   Temperature    4513 non-null   int64
 8   Crop           4513 non-null   object
 9   Fertilizer     4513 non-null   object
 10  Link           4513 non-null   object
dtypes: float64(1), int64(5), object(5)
memory usage: 388.0+ KB

In [6]:
dataset.shape

(4513, 11)

In [7]:
dataset.duplicated().sum()

0

In [8]:
dataset.describe

<bound method NDFrame.describe of      District_Name Soil_color  Nitrogen  Phosphorus  Potassium   pH  Rainfall  \
0         Kolhapur      Black        75          50        100  6.5      1000
1         Kolhapur      Black        80          50        100  6.5      1000
2         Kolhapur      Black        85          50        100  6.5      1000
3         Kolhapur      Black        90          50        100  6.5      1000
4         Kolhapur      Black        95          50        100  6.5      1000
...            ...        ...       ...         ...        ...  ...       ...
4508          Pune      Black       130          80        150  7.0      1400
4509          Pune      Black       135          80        150  7.0      1400
4510          Pune      Black       140          80        150  7.0      1400
4511          Pune      Black       145          80        150  7.0      1400
4512          Pune      Black       150          80        150  7.0      1400

      Temperature       Crop Fertilizer                          Link
0              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo
1              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo
2              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo
3              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo
4              20  Sugarcane       Urea  https://youtu.be/2t5Am0xLTOo
...           ...        ...        ...                           ...
4508           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo
4509           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo
4510           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo
4511           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo
4512           30  Sugarcane        MOP  https://youtu.be/2t5Am0xLTOo

[4513 rows x 11 columns]>

In [9]:
corr=dataset.corr(numeric_only=True)
corr

             Nitrogen  Phosphorus  Potassium        pH  Rainfall  Temperature
Nitrogen     1.000000    0.709539   0.584315  0.182850  0.269364    -0.010213
Phosphorus   0.709539    1.000000   0.573970  0.244945  0.225453    -0.055303
Potassium    0.584315    0.573970   1.000000  0.075110  0.445671     0.053413
pH           0.182850    0.244945   0.075110  1.000000  0.097884    -0.002949
Rainfall     0.269364    0.225453   0.445671  0.097884  1.000000     0.315045
Temperature -0.010213   -0.055303   0.053413 -0.002949  0.315045     1.000000

In [38]:
import ipywidgets as widgets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.ensemble import RandomForestClassifier

In [39]:
#create combo box for district_name
district_widget = widgets.Combobox(
	options=tuple(dataset['District_Name'].unique()),
	description='District:',
	placeholder='Select district',
	ensure_option=True
)

In [40]:
#Create an empty soil color widget initially
soil_color_widget = widgets.Combobox(
	description='soil color:',
	placeholder='select soil color',
	ensure_option=True
)

In [41]:
nitrogen_widget = widgets.Combobox(
	description='Nitrogen:',
    place_holder='select nitrogren value',
    ensure_option=True,
)

In [42]:
phosphorus_widget = widgets.Combobox(
	description='Phosphorus:',
    place_holder='select phosphorus value',
    ensure_option=True,
)

In [43]:
potassium_widget = widgets.Combobox(
	description='Potassium:',
    place_holder='select potassium value',
    ensure_option=True,
)

In [44]:
ph_widget = widgets.Combobox(
	description='pH:',
    place_holder='select pH value',
    ensure_option=True,
)

In [45]:
rainfall_widget = widgets.Combobox(
	description='Rainfall:',
    place_holder='select rainfall value',
    ensure_option=True,
)

In [46]:
temperature_widget = widgets.Combobox(
	description='Temperature:',
    place_holder='select temperature value',
    ensure_option=True,
)

In [47]:
recommend_widget = widgets.Output()

In [48]:
# Define the observer function to update soil color options

def update_soil_color_options (change):
  district=change.new

  if district:
    soil_colors = dataset [dataset['District_Name'] == district] ['Soil_color'].unique()
    soil_color_widget.options=tuple(soil_colors)

  else:
    soil_color_widget.options=()

In [49]:
def update_nitrogen_options(change):
    district = district_widget.value 
    soil_color = soil_color_widget.value
    if district and soil_color:
        nitrogen_values = dataset[(dataset['District Name'] == district) & (dataset['Soil_color'] == soil_color)]['Nitrogen'].unique()
        nitrogen_values = [str(value) for value in nitrogen_values] # Convert to Unicode strings
        nitrogen_widget.options = tuple(nitrogen_values)
    else:
        nitrogen_widget.options = ()

In [50]:
def update_phosphorus_options(change):
    district = district_widget.value 
    soil_color = soil_color_widget.value
    if district and soil_color:
        phosphorus_values = dataset[(dataset['District Name'] == district) & (dataset['Soil_color'] == soil_color)]['Phosphorus'].unique()
        phosphorus_values = [str(value) for value in nitrogen_values] # Convert to Unicode strings
        phosphorus_widget.options = tuple(nitrogen_values)
    else:
        phosphorus_widget.options = ()

In [51]:
def update_potassium_options(change):
    district = district_widget.value 
    soil_color = soil_color_widget.value
    if district and soil_color:
        potassium_values = dataset[(dataset['District Name'] == district) & (dataset['Soil_color'] == soil_color)]['Potassium'].unique()
        potassium_values = [str(value) for value in nitrogen_values] # Convert to Unicode strings
        potassium_widget.options = tuple(nitrogen_values)
    else:
        potassium_widget.options = ()

In [52]:
def update_ph_options(change):
    district = district_widget.value 
    soil_color = soil_color_widget.value
    if district and soil_color:
        ph_values = dataset[(dataset['District Name'] == district) & (dataset['Soil_color'] == soil_color)]['pH'].unique()
        ph_values = [str(value) for value in nitrogen_values] # Convert to Unicode strings
        ph_widget.options = tuple(nitrogen_values)
    else:
        ph_widget.options = ()

In [53]:
def update_rainfall_options(change):
    district = district_widget.value 
    soil_color = soil_color_widget.value
    if district and soil_color:
        rainfall_values = dataset[(dataset['District Name'] == district) & (dataset['Soil_color'] == soil_color)]['Rainfall'].unique()
        rainfall_values = [str(value) for value in nitrogen_values] # Convert to Unicode strings
        rainfall_widget.options = tuple(nitrogen_values)
    else:
        rainfall_widget.options = ()

In [54]:
def update_temperature_options(change):
    district = district_widget.value 
    soil_color = soil_color_widget.value
    if district and soil_color:
        temperature_values = dataset[(dataset['District Name'] == district) & (dataset['Soil_color'] == soil_color)]['Temperature'].unique()
        temperature_values = [str(value) for value in nitrogen_values] # Convert to Unicode strings
        temperature_widget.options = tuple(nitrogen_values)
    else:
        temperature_widget.options = ()

In [55]:
import pandas as pd
import ipywidgets as widgets

# Load the dataset
dataset = pd.read_csv('crop and fertilizer dataset.csv')

# Convert column names to string
dataset.columns = dataset.columns.astype(str)

# Define the available cities and soil types
cities = dataset['District_Name'].unique()
soil_types = dataset['Soil_color'].unique()

# Create a function to get the mean values for a given city and soil type
def get_mean_values(city, soil_type):
    mask = (dataset['District_Name'] == city) & (dataset['Soil_color'] == soil_type)
    subset = dataset[mask]
    mean_nitrogen = subset['Nitrogen'].mean()
    mean_phosphorus = subset['Phosphorus'].mean()
    mean_potassium = subset['Potassium'].mean()
    mean_rainfall = subset['Rainfall'].mean()
    mean_ph = subset['pH'].mean()
    return mean_nitrogen, mean_phosphorus, mean_potassium, mean_rainfall, mean_ph

# Create a function to predict the crop and fertilizer
def predict_crop_and_fertilizer(city, soil_type):
    mean_nitrogen, mean_phosphorus, mean_potassium, mean_rainfall, mean_ph = get_mean_values(city, soil_type)
    mask = (
        (dataset['District_Name'] == city) &
        (dataset['Soil_color'] == soil_type) &
        (dataset['Nitrogen'] >= mean_nitrogen) &
        (dataset['Phosphorus'] >= mean_phosphorus) &
        (dataset['Potassium'] >= mean_potassium) &
        (dataset['Rainfall'] >= mean_rainfall) &
        (dataset['pH'] >= mean_ph)
    )
    subset = dataset[mask]
    if len(subset) > 0:
        crop = subset['Crop'].values[0]
        fertilizer = subset['Fertilizer'].values[0]
        nitrogen = subset['Nitrogen'].values[0]
        phosphorus = subset['Phosphorus'].values[0]
        potassium = subset['Potassium'].values[0]
        rainfall = subset['Rainfall'].values[0]
        ph = subset['pH'].values[0]
    else:
        crop = 'Unknown'
        fertilizer = 'Unknown'
        nitrogen = 'Unknown'
        phosphorus = 'Unknown'
        potassium = 'Unknown'
        rainfall = 'Unknown'
        ph = 'Unknown'
    return crop, fertilizer, nitrogen, phosphorus, potassium, rainfall, ph

# Create interactive widgets for city and soil type selection
city_widget = widgets.Dropdown(options=cities, description='City:')
soil_widget = widgets.Dropdown(options=soil_types, description='Soil Type:')
output_widget = widgets.Output()

# Create a function to handle widget value changes
def on_change(change):
    if change['name'] == 'value':
        city = city_widget.value
        soil_type = soil_widget.value
        crop, fertilizer, nitrogen, phosphorus, potassium, rainfall, ph = predict_crop_and_fertilizer(city, soil_type)
        with output_widget:
            output_widget.clear_output()
            print('Predicted Crop:', crop)
            print('Predicted Fertilizer:', fertilizer)
            print('Nitrogen:', nitrogen)
            print('Phosphorus:', phosphorus)
            print('Potassium:', potassium)
            print('Rainfall:', rainfall)
            print('pH:', ph)

# Register the widget value change handlers
city_widget.observe(on_change)
soil_widget.observe(on_change)

# Display the widgets and output
display(widgets.VBox([city_widget, soil_widget]), output_widget)

VBox(children=(Dropdown(description='City:', options=('Kolhapur', 'Solapur', 'Satara', 'Sangli', 'Pune'), valuâ€¦

Output()